### ISSUE TITLE
Why is it so hard to make rows???

### ISSUE THREAD

**Issue by samjco** [yangm97/elementor-pro#6]
Wow. I think I may have pulled my hair out trying to easily figure how to place a full-width row inside a column.
I don't think this should be this hard in Elementor. Does it even exist?

**Comment by zgillam** [comment]
Can't you just use an Inner Section element? I suppose I might not understand what you mean.

**Comment by samjco** [comment]
@zgillam 
That what I am talking about.... I didn't know the inner section was the go-to. 
I would be better we can have an option in a column that turns it into a row, or full-width and it auto push the 2nd column to the next line. I dunno.
Or widgets for Rows and Columns

**Comment by yangm97** [comment]
Better complain at https://github.com/elementor/elementor 🤷‍♂️

Also, while you're there give this issue a thumbs up https://github.com/elementor/elementor/issues/4042
